### ISSUE TITLE
Should we setup pypi

### ISSUE THREAD

**Issue by duttonw** [qld-gov-au/ckanext-ytp-comments#78]
Hi @ThrawnCA ,

Should we install our version into https://pypi.org/project/ckanext-ytp-comments/  . Its not taken yet

**Comment by ThrawnCA** [comment]
We could, and it would likely increase the usage of our extension. Do we want the extra responsibility associated with it?

**Comment by duttonw** [comment]
Done: https://github.com/qld-gov-au/ckanext-ytp-comments/pull/122
